version: '3.4'
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - C:\Diversos\mysql:/var/lib/mysql
    networks:
      - southsystem

  back-end:
    image: gustavomoraesfonseca/south-system-test:1.0
    container_name: back-end
    ports:
      - 9091:9091
    environment:
      BOOSTRAP_SERVER: broker:9092
      MYSQL_IP: mysql
      MYSQL_USER: backend-service
      MYSQL_PASSWORD: Back@Service
    links:
      - mysql
    depends_on:
      - mysql
      - broker
    networks:
      - southsystem

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - southsystem

  broker:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - southsystem

networks:
  southsystem:
    driver: bridge